var data = [
{id:1, parent: null, codigo:"RE-01",isVisible: true, nombre: "Registro de usuarios",tipo:"Funcional",prioridad:"Alta"},
{id:2, parent: null, codigo:"RE-02",isVisible: true, nombre: "Consultar Usuario",tipo:"Funcional",prioridad:"Media"},
{id:3, parent: null, codigo:"RE-03",isVisible: true, nombre: "Modificar Usuarios",tipo:"Funcional",prioridad:"Alta"},
{id:4, parent: 1, codigo:"RE-01",isVisible: true, nombre: "Registro de usuarios",tipo:"Funcional",prioridad:"Alta"},
{id:5, parent: 1, codigo:"RE-02",isVisible: true, nombre: "Consultar Usuario",tipo:"Funcional",prioridad:"Media"},
{id:6, parent: 1, codigo:"RE-03",isVisible: true, nombre: "Modificar Usuarios",tipo:"Funcional",prioridad:"Alta"},
{id:7, parent: 1, codigo:"RE-01",isVisible: true, nombre: "Registro de usuarios",tipo:"Funcional",prioridad:"Alta"},
{id:8, parent: 1, codigo:"RE-02",isVisible: true, nombre: "Consultar Usuario",tipo:"Funcional",prioridad:"Media"},
{id:9, parent: 1, codigo:"RE-03",isVisible: true, nombre: "Modificar Usuarios",tipo:"Funcional",prioridad:"Alta"},
{id:10, parent: 1, codigo:"RE-01",isVisible: true, nombre: "Registro de usuarios",tipo:"Funcional",prioridad:"Alta"},
{id:11, parent: 1, codigo:"RE-02",isVisible: true, nombre: "Consultar Usuario",tipo:"Funcional",prioridad:"Media"},
{id:12, parent: 1, codigo:"RE-03",isVisible: true, nombre: "Modificar Usuarios",tipo:"Funcional",prioridad:"Alta"},
{id:13, parent: 1, codigo:"RE-01",isVisible: true, nombre: "Registro de usuarios",tipo:"Funcional",prioridad:"Alta"},
{id:14, parent: 1, codigo:"RE-02",isVisible: true, nombre: "Consultar Usuario",tipo:"Funcional",prioridad:"Media"},
{id:15, parent: 1, codigo:"RE-03",isVisible: true, nombre: "Modificar Usuarios",tipo:"Funcional",prioridad:"Alta"},
{id:16, parent: 1, codigo:"RE-01",isVisible: true, nombre: "Registro de usuarios",tipo:"Funcional",prioridad:"Alta"},
{id:17, parent: 1, codigo:"RE-02",isVisible: true, nombre: "Consultar Usuario",tipo:"Funcional",prioridad:"Media"},
{id:18, parent: 1, codigo:"RE-03",isVisible: true, nombre: "Modificar Usuarios",tipo:"Funcional",prioridad:"Alta"}
];